# Site settings
title: inho-woo's Gitblog
description: inho-woo's Gitblog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://inho-woo.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: inho Hwang
user_description: Web Developer
user_title: Web Developer
email: dlsgh1354@gmail.com
twitter_username: 
github_username:  inho-woo
gplus_username:  
disqus_username: 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
future: true

# html minify
compress_html:
  clippings: all
  comments: disqus
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']

# Analytics
analytics:
  provider               : "google-gtag" 
                          # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-5HQPK7RHNC"
    anonymize_ip         : # true, false (default)
